"""Tests for scripts/sync_env.py (env.yaml generator)."""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

_SCRIPT = Path(__file__).resolve().parent.parent / "scripts" / "sync_env.py"
_spec = importlib.util.spec_from_file_location("sync_env", _SCRIPT)
sync_env = importlib.util.module_from_spec(_spec)
assert _spec.loader is not None
_spec.loader.exec_module(sync_env)

PYPROJECT = """\
[project]
name = "kv-quantize"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.14.0",
    "typing_extensions>=4.15",
]
"""

LOCK = """\
version = 1
revision = 3
requires-python = ">=3.12"
resolution-markers = [
    "python_full_version < '3.14' and sys_platform != 'win32'",
]

[[package]]
name = "kv-quantize"
version = "0.1.0"
source = { virtual = "." }
dependencies = [
    { name = "accelerate" },
    { name = "typing-extensions" },
]

[[package]]
name = "accelerate"
version = "1.14.0"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "typing-extensions"
version = "4.16.0"
source = { registry = "https://pypi.org/simple" }
"""


@pytest.fixture()
def env_root(tmp_path: Path) -> Path:
    root = tmp_path
    (root / "pyproject.toml").write_text(PYPROJECT)
    (root / "uv.lock").write_text(LOCK)  # newer than pyproject.toml
    return root


def test_lock_freshness_clean(env_root: Path) -> None:
    assert sync_env.lock_freshness(env_root, env_root / "pyproject.toml") is None


def test_lock_freshness_underscore_vs_dash_normalized(env_root: Path) -> None:
    # 'typing_extensions' (pyproject) vs 'typing-extensions' (lock) are equal.
    assert "typing-extensions" in sync_env._spec_names(pyproject_deps())
    assert sync_env.lock_freshness(env_root, env_root / "pyproject.toml") is None


def pyproject_deps() -> list[str]:
    import tomllib

    return tomllib.loads(PYPROJECT)["project"]["dependencies"]


def test_lock_freshness_requires_python_mismatch(env_root: Path) -> None:
    (env_root / "pyproject.toml").write_text(PYPROJECT.replace(">=3.12", ">=3.13"))
    reason = sync_env.lock_freshness(env_root, env_root / "pyproject.toml")
    assert reason is not None and "requires-python" in reason


def test_lock_freshness_dep_set_mismatch(env_root: Path) -> None:
    (env_root / "pyproject.toml").write_text(
        PYPROJECT.replace('"typing_extensions>=4.15",', '"typing_extensions>=4.15",\n    "numpy>=2.5",')
    )
    reason = sync_env.lock_freshness(env_root, env_root / "pyproject.toml")
    assert reason is not None and "dependency set mismatch" in reason


def test_lock_freshness_missing_lock(env_root: Path) -> None:
    (env_root / "uv.lock").unlink()
    assert sync_env.lock_freshness(env_root, env_root / "pyproject.toml") == "missing"


def test_parse_export_lines() -> None:
    out = (
        "# This file is autogenerated by uv\n"
        "-e file:///Users/me/kv_quantize\n"
        "torch==2.13.0\n"
        "cuda-toolkit==13.0.3.0 ; sys_platform == 'linux'\n"
        "numpy==2.5.2\n"
    )
    pins = sync_env.parse_export_lines(out)
    assert [name for name, _ in pins] == ["torch", "cuda-toolkit", "numpy"]
    assert pins[1][1] == "cuda-toolkit==13.0.3.0 ; sys_platform == 'linux'"


def test_naive_lock_pins(env_root: Path) -> None:
    pins = dict(sync_env.naive_lock_pins(env_root))
    assert pins["accelerate"] == "accelerate==1.14.0"
    assert pins["typing-extensions"] == "typing-extensions==4.16.0"


def test_render_sorted_with_comments() -> None:
    pins = [("torch", "torch==2.13.0"), ("typing-extensions", "typing-extensions==4.16.0")]
    text = sync_env.render(pins)
    assert 'environment_version: "5"' in text
    assert text.index("  - torch==") < text.index("  - typing-extensions==")
    assert "  - typing-extensions==4.16.0  # PEP 728" in text
