"""Tests for scripts/sync_env.py (env.yaml generator)."""

from __future__ import annotations

import importlib.util
import subprocess
from pathlib import Path

import pytest

_SCRIPT = Path(__file__).resolve().parent.parent / "scripts" / "sync_env.py"
_spec = importlib.util.spec_from_file_location("sync_env", _SCRIPT)
sync_env = importlib.util.module_from_spec(_spec)
assert _spec.loader is not None
_spec.loader.exec_module(sync_env)

def test_parse_export_lines() -> None:
    out = (
        "# This file is autogenerated by uv\n"
        "-e file:///Users/me/kv_quantize\n"
        "torch==2.13.0\n"
        "cuda-toolkit==13.0.3.0 ; sys_platform == 'linux'\n"
        "numpy==2.5.2\n"
    )
    pins = sync_env.parse_export_lines(out)
    assert [name for name, _ in pins] == ["torch", "cuda-toolkit", "numpy"]
    assert pins[1][1] == "cuda-toolkit==13.0.3.0 ; sys_platform == 'linux'"


def test_parse_export_lines_rejects_unknown_output() -> None:
    with pytest.raises(ValueError, match="unrecognized uv export line"):
        sync_env.parse_export_lines("local-package @ file:///tmp/local")


def test_run_uv_fails_closed(monkeypatch, tmp_path: Path) -> None:
    def failed(*args, **kwargs):
        return subprocess.CompletedProcess(args[0], 2, stdout="", stderr="lock is stale")

    monkeypatch.setattr(sync_env.subprocess, "run", failed)
    with pytest.raises(SystemExit, match="lock is stale"):
        sync_env.run_uv(["lock", "--check"], tmp_path)


def test_render_sorted_with_comments() -> None:
    pins = [("torch", "torch==2.13.0"), ("typing-extensions", "typing-extensions==4.16.0")]
    text = sync_env.render(pins)
    assert 'environment_version: "5"' in text
    assert text.index("  - torch==") < text.index("  - typing-extensions==")
    assert "  - typing-extensions==4.16.0  # PEP 728" in text
