"""Sync env.yaml (Databricks custom env) from pyproject.toml + uv's resolution.

env.yaml pins the **full resolved closure** of the project's runtime deps,
produced by `uv export` from uv.lock: a Databricks *custom* environment is
built from nothing (no preinstalled torch), so everything must be declared —
including torch, which accelerate pulls in transitively. Pinning the closure
means Databricks gets exactly what `uv sync` resolved locally, markers
included (pip evaluates `; python_full_version ...` markers on the 3.12
Databricks runtime).

Derivation rules:
  - the dependency *set*: pyproject.toml `[project].dependencies` plus the
    `eval` extra (dev groups are excluded);
  - the *versions*: uv.lock, regenerated by `uv lock` when uv's content-based
    freshness oracle (`uv lock --check`) reports the lock out of date (this
    catches requires-python, dependency-set *and* version-floor edits);
  - nothing is excluded: torch is pinned like any other package.

Wiring:
  - uv:  `uv run --no-project python scripts/sync_env.py` is the uv-native
         invocation; the script runs `uv lock` itself when the lock is stale.
  - git: .githooks/pre-commit runs this on any commit that touches
         pyproject.toml (activate once: git config core.hooksPath .githooks).
  - CI:  `python scripts/sync_env.py --check` exits 1 when env.yaml is stale.

Usage:
    python scripts/sync_env.py             # rewrite env.yaml
    python scripts/sync_env.py --check     # read-only freshness check
"""

from __future__ import annotations

import argparse
import difflib
import shutil
import subprocess
import sys
from pathlib import Path

try:
    ROOT = Path(__file__).resolve().parent.parent
except NameError:
    # Databricks notebooks don't define __file__; the notebook's directory
    # (the repo root there) is already the cwd.
    ROOT = Path.cwd()
PYPROJECT = ROOT / "pyproject.toml"
ENV_YAML = ROOT / "env.yaml"

# Databricks custom-environment version: "5" == Python 3.12.3 (see env.yaml).
ENVIRONMENT_VERSION = "5"

# Trailing comments carried into env.yaml for individual pins.
PIN_COMMENTS = {
    "numpy": "fibquant/codebook.py imports numpy directly for Beta-quantile radii",
    "typing-extensions": "PEP 728 extra_items backport for lm-eval 0.4.12 on py3.12",
}

EXPORT_CMD = [
    "uv", "export",
    "--format", "requirements-txt",
    "--no-hashes",
    "--no-header",
    "--no-dev",
    "--no-emit-project",
    "--extra",
    "eval",
]


def parse_export_lines(text: str) -> list[tuple[str, str]]:
    """Parse `uv export` stdout into (name, requirement-line) pairs."""
    pins: list[tuple[str, str]] = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("-e ") or line.startswith("-"):
            continue
        name, separator, version = line.partition("==")
        if not separator or not name or not version:
            raise ValueError(f"unrecognized uv export line: {line!r}")
        pins.append((name.split("[", 1)[0].replace("_", "-").lower(), line))
    return pins


def run_uv(args: list[str], root: Path) -> str:
    """Run uv or stop: generated environment state must never be approximate."""
    proc = subprocess.run(["uv", *args], cwd=root, capture_output=True, text=True)
    if proc.returncode != 0:
        raise SystemExit(
            f"`uv {' '.join(args)}` failed (rc={proc.returncode}): "
            f"{proc.stderr.strip() or proc.stdout.strip() or 'see uv output'}"
        )
    return proc.stdout


def export_pins(root: Path) -> list[tuple[str, str]]:
    """Export the exact locked core + eval dependency closure."""
    return parse_export_lines(run_uv(EXPORT_CMD[1:], root))


def render(pins: list[tuple[str, str]]) -> str:
    lines = [
        "# Serverless custom environment for the FibQuant CUDA eval (scripts/eval_cuda.py).",
        "#",
        "# GENERATED by scripts/sync_env.py -- do not hand-edit version pins. Edit",
        "# pyproject.toml (runtime deps) and re-run `python scripts/sync_env.py`; the",
        "# git pre-commit hook (.githooks/) does this automatically on pyproject.toml",
        "# changes.",
        "#",
        "# Attach: notebook Environment side pane > Base environment > Custom > select this file.",
        f"# Python comes from environment_version ('{ENVIRONMENT_VERSION}' = 3.12.3, newest; no 3.13 environment",
        "# exists yet, but a clean env + typing_extensions>=4.15 covers lm-eval's PEP 728",
        "# extra_items TypedDict on 3.12).",
        "#",
        "# Custom environments are built from scratch (nothing preinstalled), so this",
        "# pins the FULL resolved closure from uv.lock (`uv export`) -- torch included.",
        "# Requirements with `;` markers are evaluated by pip on the 3.12 runtime.",
        f'environment_version: "{ENVIRONMENT_VERSION}"',
        "dependencies:",
    ]
    for name, line in sorted(pins):
        rendered = f"  - {line}"
        comment = PIN_COMMENTS.get(name)
        if comment:
            rendered += f"  # {comment}"
        lines.append(rendered)
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if env.yaml is stale (no writes)")
    ap.add_argument("--pyproject", type=Path, default=PYPROJECT, help=argparse.SUPPRESS)
    ap.add_argument("--env-yaml", type=Path, default=ENV_YAML, help=argparse.SUPPRESS)
    args = ap.parse_args(argv)

    root = args.pyproject.parent
    if shutil.which("uv") is None:
        raise SystemExit("uv is required to synchronize env.yaml")

    if args.check:
        run_uv(["lock", "--check"], root)
    else:
        run_uv(["lock"], root)
    pins = export_pins(root)

    rendered = render(pins)
    current = args.env_yaml.read_text() if args.env_yaml.is_file() else None
    if current == rendered:
        print(f"{args.env_yaml} is up to date")
        return 0
    if args.check:
        diff = difflib.unified_diff(
            (current or "").splitlines(), rendered.splitlines(),
            fromfile=str(args.env_yaml), tofile="(generated)", lineterm="",
        )
        print("\n".join(diff))
        print(f"\n{args.env_yaml} is stale -- run `python scripts/sync_env.py`", file=sys.stderr)
        return 1

    args.env_yaml.write_text(rendered)
    print(f"wrote {args.env_yaml} ({len(pins)} pinned requirements)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
