"""Sync env.yaml (Databricks custom env) from pyproject.toml + uv's resolution.

env.yaml pins the **full resolved closure** of the project's runtime deps,
produced by `uv export` from uv.lock: a Databricks *custom* environment is
built from nothing (no preinstalled torch), so everything must be declared —
including torch, which accelerate pulls in transitively. Pinning the closure
means Databricks gets exactly what `uv sync` resolved locally, markers
included (pip evaluates `; python_full_version ...` markers on the 3.12
Databricks runtime).

Derivation rules:
  - the dependency *set*: pyproject.toml `[project].dependencies` (dev groups
    are excluded; add one only if the Databricks env needs it);
  - the *versions*: uv.lock, regenerated by `uv lock` when uv's content-based
    freshness oracle (`uv lock --check`) reports the lock out of date (this
    catches requires-python, dependency-set *and* version-floor edits);
  - nothing is excluded: torch is pinned like any other package.

Wiring:
  - uv:  `uv run --no-project python scripts/sync_env.py` is the uv-native
         invocation; the script runs `uv lock` itself when the lock is stale.
  - git: .githooks/pre-commit runs this on any commit that touches
         pyproject.toml (activate once: git config core.hooksPath .githooks).
  - CI:  `python scripts/sync_env.py --check` exits 1 when env.yaml is stale.

Usage:
    python scripts/sync_env.py             # rewrite env.yaml
    python scripts/sync_env.py --check     # read-only freshness check
    python scripts/sync_env.py --no-uv     # offline: parse uv.lock directly
"""

from __future__ import annotations

import argparse
import difflib
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

try:
    ROOT = Path(__file__).resolve().parent.parent
except NameError:
    # Databricks notebooks don't define __file__; the notebook's directory
    # (the repo root there) is already the cwd.
    ROOT = Path.cwd()
PYPROJECT = ROOT / "pyproject.toml"
ENV_YAML = ROOT / "env.yaml"

# Databricks custom-environment version: "5" == Python 3.12.3 (see env.yaml).
ENVIRONMENT_VERSION = "5"

# Trailing comments carried into env.yaml for individual pins.
PIN_COMMENTS = {
    "numpy": "fibquant/codebook.py imports numpy directly (SparseStem/radii)",
    "typing_extensions": "PEP 728 extra_items backport for lm-eval 0.4.12 on py3.12",
}

EXPORT_CMD = [
    "uv", "export",
    "--format", "requirements-txt",
    "--no-hashes",
    "--no-header",
    "--no-dev",
    "--no-emit-project",
]


def _norm(name: str) -> str:
    """PEP 503 normalization (underscores and hyphens are equivalent)."""
    return name.replace("_", "-").lower()


# Same lookup keys, normalized.
PIN_COMMENTS_NORM = {_norm(k): v for k, v in PIN_COMMENTS.items()}


def _spec_names(specs: list[str]) -> set[str]:
    names: set[str] = set()
    for spec in specs:
        m = re.match(r"\s*([A-Za-z0-9_.-]+)(\[[^\]]*\])?\s*[<>=!~;]", spec)
        if m:
            names.add(_norm(m.group(1)))
        else:
            raise ValueError(f"unrecognized dependency spec: {spec!r}")
    return names


def lock_freshness(root: Path, pyproject: Path) -> str | None:
    """Why uv.lock is stale, or None when it matches pyproject.toml."""
    lock = root / "uv.lock"
    if not lock.is_file():
        return "missing"
    try:
        lock_data = tomllib.loads(lock.read_text())
    except tomllib.TOMLDecodeError as e:
        return f"unparsable ({e})"
    try:
        proj_data = tomllib.loads(pyproject.read_text())["project"]
    except (tomllib.TOMLDecodeError, KeyError) as e:
        return f"pyproject.toml unparsable ({e})"

    if lock_data.get("requires-python") != proj_data.get("requires-python"):
        return (
            f"requires-python mismatch ({lock_data.get('requires-python')!r} vs "
            f"{proj_data.get('requires-python')!r})"
        )
    # The project's direct deps live in its own [[package]] entry in uv.lock.
    project_pkg = next(
        (p for p in lock_data.get("package", []) if p.get("name") == proj_data.get("name")),
        None,
    )
    lock_deps = {_norm(d["name"]) for d in (project_pkg or {}).get("dependencies", [])}
    proj_deps = _spec_names(proj_data.get("dependencies", []))
    if lock_deps != proj_deps:
        return (
            f"dependency set mismatch (only lock: {sorted(lock_deps - proj_deps)}, "
            f"only project: {sorted(proj_deps - lock_deps)})"
        )
    if lock.stat().st_mtime < pyproject.stat().st_mtime:
        return "older than pyproject.toml"
    return None


def parse_export_lines(text: str) -> list[tuple[str, str]]:
    """Parse `uv export` stdout into (name, requirement-line) pairs."""
    pins: list[tuple[str, str]] = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("-e ") or line.startswith("-"):
            continue
        if not re.match(r"^[A-Za-z0-9_.-]+(?:\[[^\]]*\])?==[^;\s]+(\s*;.*)?$", line):
            print(f"warning: skipping unparsed export line: {line!r}", file=sys.stderr)
            continue
        pins.append((line.split("==", 1)[0], line))
    return pins


def export_pins(root: Path) -> list[tuple[str, str]]:
    """Run `uv export`; return (name, requirement-line) pairs."""
    proc = subprocess.run(EXPORT_CMD, cwd=root, capture_output=True, text=True)
    if proc.returncode != 0:
        raise SystemExit(
            f"`uv export` failed (rc={proc.returncode}): {proc.stderr.strip() or 'see uv'}"
        )
    return parse_export_lines(proc.stdout)


def naive_lock_pins(root: Path) -> list[tuple[str, str]]:
    """Offline fallback (--no-uv): parse uv.lock directly, max version per name.

    This ignores platform/python markers, so it may over-pin versions that
    only apply to other resolution branches; prefer `uv export`.
    """
    data = tomllib.loads((root / "uv.lock").read_text())
    best: dict[str, str] = {}
    for pkg in data.get("package", []):
        name, version = pkg["name"], pkg["version"]
        if version > best.get(name, ""):
            best[name] = version
    return [(name, f"{name}=={version}") for name, version in best.items()]


def render(pins: list[tuple[str, str]]) -> str:
    lines = [
        "# Serverless custom environment for the FibQuant CUDA eval (scripts/eval_cuda.py).",
        "#",
        "# GENERATED by scripts/sync_env.py -- do not hand-edit version pins. Edit",
        "# pyproject.toml (runtime deps) and re-run `python scripts/sync_env.py`; the",
        "# git pre-commit hook (.githooks/) does this automatically on pyproject.toml",
        "# changes.",
        "#",
        "# Attach: notebook Environment side pane > Base environment > Custom > select this file.",
        f"# Python comes from environment_version ('{ENVIRONMENT_VERSION}' = 3.12.3, newest; no 3.13 environment",
        "# exists yet, but a clean env + typing_extensions>=4.15 covers lm-eval's PEP 728",
        "# extra_items TypedDict on 3.12).",
        "#",
        "# Custom environments are built from scratch (nothing preinstalled), so this",
        "# pins the FULL resolved closure from uv.lock (`uv export`) -- torch included.",
        "# Requirements with `;` markers are evaluated by pip on the 3.12 runtime.",
        f'environment_version: "{ENVIRONMENT_VERSION}"',
        "dependencies:",
    ]
    for name, line in sorted(pins):
        rendered = f"  - {line}"
        comment = PIN_COMMENTS_NORM.get(_norm(name))
        if comment:
            rendered += f"  # {comment}"
        lines.append(rendered)
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if env.yaml is stale (no writes)")
    ap.add_argument("--no-uv", action="store_true", help="offline: parse uv.lock directly, no uv subprocess")
    ap.add_argument("--pyproject", type=Path, default=PYPROJECT, help=argparse.SUPPRESS)
    ap.add_argument("--env-yaml", type=Path, default=ENV_YAML, help=argparse.SUPPRESS)
    args = ap.parse_args(argv)

    root = args.pyproject.parent
    write = not args.check

    if args.no_uv or shutil.which("uv") is None:
        pins = naive_lock_pins(root)
        print(
            "warning: --no-uv (or uv not on PATH): parsed uv.lock directly, markers "
            "ignored; run plain `python scripts/sync_env.py` for accuracy",
            file=sys.stderr,
        )
    else:
        # uv's own content-based freshness oracle (covers floor-only edits too).
        proc = subprocess.run(["uv", "lock", "--check"], cwd=root, capture_output=True, text=True)
        if proc.returncode == 0:
            reason = None
        else:
            detail = (proc.stderr or proc.stdout).strip().splitlines()
            reason = detail[-1] if detail else f"rc={proc.returncode}"
        if reason and write:
            proc = subprocess.run(["uv", "lock"], cwd=root, capture_output=True, text=True)
            if proc.returncode != 0:
                print(
                    f"warning: `uv lock` could not regenerate the lock ({reason}); "
                    f"proceeding with the existing lock",
                    file=sys.stderr,
                )
        elif reason:
            print(
                f"warning: lock is stale ({reason}); run without --check to regenerate it",
                file=sys.stderr,
            )
        pins = export_pins(root)

    rendered = render(pins)
    current = args.env_yaml.read_text() if args.env_yaml.is_file() else None
    if current == rendered:
        print(f"{args.env_yaml} is up to date")
        return 0
    if args.check:
        diff = difflib.unified_diff(
            (current or "").splitlines(), rendered.splitlines(),
            fromfile=str(args.env_yaml), tofile="(generated)", lineterm="",
        )
        print("\n".join(diff))
        print(f"\n{args.env_yaml} is stale -- run `python scripts/sync_env.py --write`", file=sys.stderr)
        return 1

    args.env_yaml.write_text(rendered)
    print(f"wrote {args.env_yaml} ({len(pins)} pinned requirements)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
